config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "pages#home"
  
  get "products/veriklick", to: "pages#veriklick"
  get "products/veridial", to: "pages#veridial"
  get "products/verisource", to: "pages#verisource"
  get "pricing", to: "pages#pricing"
  get "demo", to: "pages#demo"
  get "get-started", to: "pages#get_started"
  get "contact", to: "pages#contact"
  get "support", to: "pages#support"
  get "about", to: "pages#about"
  get "careers", to: "pages#careers"
  get "registration", to: "pages#registration"
  get "blog", to: "pages#blog"
  get "blog/winning-the-war-for-talent-it-all-depends-on-ai", to: "pages#article_one", as: "article_one"
  get "blog/verification-with-a-klick-hire-right-the-first-time", to: "pages#article_two", as: "article_two"
  get "blog/best-recruiting-practices-series-answering-your-questions", to: "pages#article_three", as: "article_three"
  get "blog/best-recruiting-practices-2018", to: "pages#article_four", as: "article_four"
  get "blog/synkriom-the-onestop-shop-for-verified-resources", to: "pages#article_five", as: "article_five"
  get "blog/new-tech-aims-to-id-deceptive-candidates", to: "pages#article_six", as: "article_six"
  get "login", to: "pages#login"
  get "signup", to: "pages#signup"
  
  get "video", to: "pages#video"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home 
  end
  
  def veriklick
  end
  
  def veridial
  end
  
  def verisource
  end
  
  def pricing
  end
  
  def demo 
  end
  
  def get_started 
  end 
  
  def contact 
  end
  
  def support
  end
  
  def about 
  end
  
  def careers 
  end
  
  def registration
  end
  
  def blog 
  end
  
  def article_one 
  end 
  
  def article_two
  end
  
  def article_three
  end
  
  def article_four
  end
  
  def article_five
  end
  
  def article_six
  end
  
  def login 
  end
  
  def signup 
  end
  
  def video 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>VeriKlick</title>
    <%= csrf_meta_tags %>
    <link rel="icon" href="<%= asset_path('favicon-32x32.png') %>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <% unless action_name == "video" %>
      <%= render "shared/mobile-header" %>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/blog.html.haml
=render "shared/top_header"
=render "shared/logo_menu_bar"
%section.radial-gradient-top.pt-140.pb-160
  .container
    %h2.text-center
      Blog
    .red-spacer.mx-auto
%section.blog-one.gray-wave.gray-wave-bottom
  .container
    .row.align-items-stretch
      .col-lg-4.col-md-6.px-4.mb-5
        .card.h-100.borderless
          =image_tag "robot.png", class: "card-img-top mb-3"
          .card-body.pt-4.px-25
            %h3.text-blue
              Winning the 
              %span.text-red War for Talent:
              It All Depends on AI
            %p.fine-print
              January 10, 2019 By KOMAL DANGI
            %p
              While some recruiters and HR pros are concerned that artificial 
              intelligence (AI) is replacing them,
            =link_to "Read More", article_one_path, class: "btn btn-outline-dark px-4 py-2" 
      .col-lg-4.col-md-6.px-4.mb-5
        .card.h-100.borderless
          =image_tag "cloud-computing.jpg", class: "card-img-top mb-3"
          .card-body.pt-4.px-25
            %h3.text-blue
              Verification With a Klick:
              %span.text-red Hire Right the First Time!
            %p.fine-print
              August 2018 By KOMAL DANGI
            %p
              Even in today’s talent-driven labor market where job openings 
              outnumber talent supply, job 
            =link_to "Read More", article_two_path, class: "btn btn-outline-dark px-4 py-2" 
      .col-lg-4.col-md-6.px-4.mb-5
        .card.h-100.borderless
          =image_tag "mass-recruiting-1024x682.jpg", class: "card-img-top mb-3"
          .card-body.pt-4.px-25
            %h3.text-red
              Best Recruting Practices
              %span.text-blue 
                Series-Answering Your Questions 
            %p.fine-print
              November 2018 By KOMAL DANGI
            %p
              Last month, I addressed some questions we have received from 
              recruiting professionals who 
            =link_to "Read More", article_three_path, class: "btn btn-outline-dark px-4 py-2" 
      .col-lg-4.col-md-6.px-4.mb-5
        .card.h-100.borderless
          =image_tag "resume1.jpg", class: "card-img-top mb-3"
          .card-body.pt-4.px-25
            %h3.text-red
              Best Recruting Practices
              %span.text-blue - 2018
            %p.fine-print
              November 2018 By: KOMAL DANGI
            %p
              This month, I am going to address some of the burning questions 
              we have received from recruiting 
            =link_to "Read More", article_four_path, class: "btn btn-outline-dark px-4 py-2" 
      .col-lg-4.col-md-6.px-4.mb-5
        .card.h-100.borderless
          =image_tag "tim-gouw-79563-unsplash.jpg", class: "card-img-top mb-3"
          .card-body.pt-4.px-25
            %h3.text-blue
              Synkriom: The One-Stop Shop for 
              %span.text-red Verified Resources
            %p.fine-print
              November 2018
            %p
              Nudged by a competitive job environment, stories of resume 
              inflation are a common occurrence
            =link_to "Read More", article_five_path, class: "btn btn-outline-dark px-4 py-2" 
      .col-lg-4.col-md-6.px-4.mb-5
        .card.h-100.borderless
          =image_tag "rawpixel-788601-unsplash.jpg", class: "card-img-top mb-3"
          .card-body.pt-4.px-25
            %h3.text-blue
              New Tech Aims to
              %span.text-red 
                ID Deceptive Candidates
            %p.fine-print
              December 5, 2018 By: Caroline Hroncich
            %p
              One technology company thinks they may have a way to verify 
              candidates that are lying about 
            =link_to "Read More", article_six_path, class: "btn btn-outline-dark px-4 py-2" 
    .row
      .col-auto.mx-auto
        %nav{"aria-label" => "Page navigation example"}
          %ul.pagination
            %li.page-item
              %a.page-link{:href => "#"} Previous
            %li.page-item
              %a.page-link{:href => "#"} 1
            %li.page-item
              %a.page-link{:href => "#"} 2
            %li.page-item
              %a.page-link{:href => "#"} 3
            %li.page-item
              %a.page-link{:href => "#"} Next


=render "shared/footer"

app/views/pages/home.html.haml
=render "shared/top_header"
%section.home-page-title
  .home-header-bg
    .container-fluid.d-none.d-lg-block
      .row.align-items-center.py-3
        .col-4.justify-content-start
          =link_to root_path, class: "logo" do 
            =image_tag "VeriKlick-Logo.png"
        .col-8.justify-content-end
          %ul.nav.justify-content-end#bold-menu
            %li.nav-item 
              =link_to "Products", "#", class: "nav-link red-underlined"
              .nav-block
                .row.p-2
                  .col-lg-4.px-3
                    =link_to products_veriklick_path do 
                      .p-2
                        %h3.text-blue<
                          Veri
                          %span.text-red> Klick
                        %p.text-med-gray
                          Recruiting Platform
                  .col-lg-4.px-3
                    =link_to products_veridial_path do 
                      .p-2
                        %h3.text-blue<
                          Veri
                          %span.text-red> Dial
                        %p.text-med-gray
                          Recruiting Dialer
                  .col-lg-4.px-3
                    =link_to products_verisource_path do 
                      .p-2
                        %h3.text-blue<
                          Veri
                          %span.text-red> Source
                        %p.text-med-gray
                          Candidate Sourcing
            %li.nav-item 
              =link_to "Pricing", pricing_path, class: "nav-link red-underlined"
            %li.nav-item 
              =link_to "Demo", demo_path, class: "nav-link red-underlined"
            %li.nav-item
              =link_to "Get Started", get_started_path, class: "nav-link btn btn-get-started"
    .container-fluid
      .row.align-items-center
        .col-lg-6.col-with-text
          %h1.text-blue 
            Find and verify 
            %br.d-lg-block.d-none
            the
            %span.text-red right hire, faster
          .red-spacer
          %p.text-large.text-blue.mw-720
            VeriKlick provides total talent management with the 
            power of verified resources and vendor pool in a single platform
          =link_to signup_path, class: "btn btn-big-red mt-3" do
            Get My Free Demo 
            =icon "fas", "angle-down"
        .col-6.col-with-image.d-none.d-lg-block
          =image_tag "home-section-1-image.png", 
                     class: "float-right img-fluid"
%section.home-two
  .container.my-5.py-5
    .row.align-items-center
      .col-6.d-none.d-lg-block
        .row
          .col-6.px-15.mb-5
            =image_tag "search-box-1.png", class: "img-fluid hover-grow"
          .col-6.px-15.mb-5
            =image_tag "verify-box-2.png", class: "img-fluid hover-grow"
          .col-6.px-15.mb-5
            =image_tag "interview-box-3.png", class: "img-fluid hover-grow"
          .col-6.px-15.mb-5
            =image_tag "hire-box-4.png", class: "img-fluid hover-grow"
      .col-lg-6
        %h2.text-blue
          Your
          %span.text-red One-Stop
          Hiring and Recruting
          %span.text-red Platform
        .red-spacer
        %p
          By combining our proprietary AI and unparalleled access to global 
          candidate data, we can help you quickly identify, contact, verify, 
          and hire the right person—no matter how specialized the position. 
        %p
          And did we mention… all of our tools are completely customizable to 
          your specific needs.
%section.home-three.gray-clouds
  .gray-cloud-bg
    .container
      .row
        .col-10.mx-auto
          %h2.text-center.text-blue.pb-3
            Streamline
            %span.text-red Candidate Verification
          %p.text-center.d-none.d-lg-block
            VeriKlick is the only platform to use patented technology with real-time 
            data to verify candidates at every stage of the hiring pipeline to ensure 
            you are interviewing, recruiting, and hiring the right people.
      =image_tag "section-3-image-without-buttons.png", class: "img-fluid big-circle-bg d-none d-lg-block"
      .circles
        =link_to products_veriklick_path do 
          .circle-text#circle-one
            =render "shared/icons/ID-verification"
            ID Verification
        =link_to products_veriklick_path do 
          .circle-text#circle-two
            =render "shared/icons/intelligent-resume-filtering"
            Intelligent Resume Filtering
        =link_to products_veriklick_path do 
          .circle-text#circle-three
            =render "shared/icons/reference-checks"
            Reference Checks
        =link_to products_veriklick_path do 
          .circle-text#circle-four
            =render "shared/icons/video-live-chat"
            Video + Live Chat Interviews 
        =link_to products_veriklick_path do 
          .circle-text#circle-five
            =render "shared/icons/biometrics"
            Biometrics 
            %br
            (Face &amp; Voice Verification)
        =link_to products_veriklick_path do 
          .circle-text#circle-six
            =render "shared/icons/technical-screening"
            Techincal Screening
        =link_to products_veriklick_path do 
          .circle-text.green-circle#circle-seven
            =render "shared/icons/verified-candidates"
            Verified candidates &amp; Resumes
%section.home-four.white-wave.overlap-420
  .white-wave-bg 
    .container.mb-5.pb-5
      .row.align-items-center
        .col-6.d-none.d-lg-block
          =image_tag "home-section-4-image.png", class: "img-fluid"
        .col-lg-6
          %h6.text-blue Find Candidates
          %h2.text-red 
            AI Powered
            %span.text-blue Search 
          .red-spacer
          %ul.caret-bullets
            %li 
              Input simple or specialized position criteria and sit back as 
              qualified candidate options populate in your VeriKlick dashboard
            %li 
              Access our unmatched vendor pool of over 400+ technical talent
              suppliers
            %li
              VeriKlick's intelligent search feature filters and eliminates 
              falsified resumes and bogus candidates
          =link_to signup_path, class: "btn btn-big-red mt-3" do
            Learn More
            =icon "fas", "angle-down"
%section.home-five.gray-wave
  .gray-wave-bg
    .container
      .row.align-items-center
        .col-lg-6
          %h6.text-blue Recruit Candidates 
          %h2.text-blue 
            Automated
            %span.text-red Personalized Outreach
          .red-spacer
          %ul.caret-bullets
            %li
              Contact and speak to more candidates by using the only dialer 
              system designed specifically for recruiting and hiring
            %li
              Send and receive messages from qualified candidates and easily 
              manage every step of the recruiting pipeline
            %li
              Generate impressive communication reports with play-by-play data 
              from every candidate interaction 
          =link_to signup_path, class: "btn btn-big-red mt-3" do
            Learn More
            =icon "fas", "angle-down"
        .col-6.d-none.d-lg-block
          =image_tag "home-section-5-image.png", class: "img-fluid px-80"
%section.home-six.white-wave-2
  .white-wave-2-bg
    .container
      .row.align-items-center 
        .col-6.d-none.d-lg-block
          =image_tag "home-section-6-without-yellow-ladder.png", class: "img-fluid", id: "green-ladders"
          =image_tag "home-section-6-yellow-ladder.png", class: "img-fluid", id: "yellow-ladder"
        .col-lg-6
          %h6.text-blue Verify Candidates
          %h2.text-red
            Intelligent
            %span.text-blue Candidate Verification with
            Voice Mapping
          .red-spacer 
          %ul.caret-bullets
            %li
              Verify a candidate’s ID, experience, references and much more
            %li
              Live chat with colleagues about candidates during video interviews
            %li
              Receive real-time candidate verification data with VeriKlick’s 
              biometric technology
          =link_to signup_path, class: "btn btn-big-red mt-3" do
            Learn More
            =icon "fas", "angle-down"
%section.home-seven.gray-wave.pb-140
  .gray-wave-bg
    .container 
      .row.align-items-center
        .col-lg-6
          %h6.text-blue Hire Candidates 
          %h2.text-red 
            Scalable
            %span.text-blue Hiring
            Solutions
          .red-spacer
          %ul.caret-bullets 
            %li 
              Who is VeriKlick built for? Independent recruiters, talent 
              suppliers, enterprise companies, and can be customized for 
              everyone in between.
            %li 
              Finally, a complete beginning-to-end solution that decreases your 
              cost-per-hire and frees up your time and internal resources
          =link_to signup_path, class: "btn btn-big-red mt-3" do
            Learn More
            =icon "fas", "angle-down"
        .col-6.d-none.d-lg-block
          =image_tag "greenflag65.gif", class: "img-fluid mb--160"
%section.home-eight.white-wave.white-wave-bottom
  .white-wave-bg 
    .container
      .row.mb-5
        .col.text-center
          %h2.text-blue
            Take Hiring to the
            %span.text-red Next Level 
          .red-spacer.mx-auto 
          %p
            3 powerful solutions to lead you to the best candidates faster
      .row.pb-5
        .col-lg-4.mb-5
          .trial-card#blue-card
            =render "shared/icons/clock_icon"
            %p.text-center
              Employee Recruitment Dialer
            %h2.text-center.text-blue
              VeriDial
            %p
              The first ever dialer designed for recruiting and hiring
            %ul 
              %li 
                Create job criteria based campaigns
              %li
                Completely customizable to your unique needs 
              %li
                Detailed campaign reporting 
              %li 
                Forcast agent occupancy and workload 
            =link_to "Start Trial", signup_path, class: "btn btn-trial"
        .col-lg-4.mb-5
          .trial-card#purple-card
            =render "shared/icons/presentation_icon"
            %p.text-center 
              Intelligent Candidate Verification
            %h2.text-blue.text-center
              VeriKlick
            %p
              Automate candidate verification and eliminate falsified resumes
            %ul
              %li 
                Search qualified candidates
              %li 
                Automate resume filtering
              %li 
                Verify employment and experience
              %li 
                Secure video interviewing capabilities
            =link_to "Start Trial", signup_path, class: "btn btn-trial"
        .col-lg-4.mb-5
          .trial-card#red-card 
            =render "shared/icons/rook_icon"
            %p.text-center
              Full-Service Candidate Sourcing 
            %h2.text-blue.text-center
              VeriSource 
            %p
              Our hands off recruiting solution — powered by our industry 
              leading talent advisors
            %ul
              %li
                Hands off, worry free solution for finding the perfect hire
              %li
                Unlimited access and communication with our talent advisors
              %li
                Interview-ready candidates, passed on to your hiring managers
            =link_to "Start Trial", signup_path, class: "btn btn-trial"
=render "shared/footer"


:javascript 
  $(window).scroll(function(){
    var top = $(window).scrollTop();
    if( top >= 3800 && top <= 4640) {
      var bottom = ( (top - 3800) / 3.5) - 440
      $("#yellow-ladder").css("bottom", bottom + "px");
    }
  });

app/views/shared/_address.html.haml
VeriKlick Headquarters 
%br 
One Gateway Center
%br 
Suite 2600 
%br 
Newark, NJ 07102 

app/views/shared/_blog-sidebar.html.haml
.card.borderless.shadowed.mb-5
  .card-body
    %input.borderless{ :placeholder => "Search post..."}
.card.borderless.shadowed.mb-5
  .card-body
    %h4 Categories
    %table.w-100
      %tr 
        %td
          =link_to "Recruting Strategies", "#"
        %td.text-right
          (8)
.card.borderless.shadowed.mb-5
  .card-body
    %h4 Popular Posts
    .mb-5.clearfix
      =link_to article_one_path do 
        =image_tag "john-schnobrich-520022-unsplash.jpg", 
                    class: "img-thumb mr-3 float-left"
        %h5 Winning the&hellip;
        %p.fine-print 150 views
    .mb-5.clearfix
      =link_to article_two_path do 
        =image_tag "cloud-computing-72x72.jpg", 
                    class: "img-thumb mr-3 float-left"
        %h5 Verification&hellip;
        %p.fine-print 150 views
    .mb-5.clearfix
      =link_to article_three_path do 
        =image_tag "mass-recruiting-72x72.jpg", 
                    class: "img-thumb mr-3 float-left"
        %h5 Best Recruiting&hellip;
        %p.fine-print 150 views
    .mb-5.clearfix
      =link_to article_four_path do 
        =image_tag "resume1-72x72.jpg", 
                    class: "img-thumb mr-3 float-left"
        %h5 Best Recruiting&hellip;
        %p.fine-print 150 views
.card.borderless.shadowed.mb-5
  .card-body
    %h4 Archives
    %p
      =link_to "October 2018", "#"

app/views/shared/_bottom_footer.html.haml
%footer 
  .container
    .row
      .col-lg-3
        =link_to root_path do 
          =image_tag "VeriKlick-Logo.png"
        %p.d-none
          VeriKlick is a one-stop tool that intelligently streamlines your 
          ability to find and hire the best candidates all over the world
      .col-lg-6.py-5.py-lg-0
        .row.text-center.text-lg-left
          .col-md-3.col-6
            %ul.footer-links
              %li
                =link_to "Products", "#", class: "footer-list-header"
              %li 
                =link_to "VeriKlick", products_veriklick_path, class: "footer-list-item"
              %li 
                =link_to "VeriDial", products_veridial_path, class: "footer-list-item"
              %li 
                =link_to "VeriSource", products_verisource_path, class: "footer-list-item"
          .col-md-3.col-6
            %ul.footer-links
              %li
                =link_to "Company", "#", class: "footer-list-header"
              %li 
                =link_to "About us", about_path, class: "footer-list-item"
              %li 
                =link_to "Careers", careers_path, class: "footer-list-item"
          .col-md-3.col-6
            %ul.footer-links
              %li
                =link_to "Library", "#", class: "footer-list-header"
              %li 
                =link_to "Blog", blog_path, class: "footer-list-item"
              %li
                =link_to "Pricing", pricing_path, class: "footer-list-header"
              %li
                =link_to "Demo", demo_path, class: "footer-list-header"
          .col-md-3.col-6
            %ul.footer-links
              %li
                =link_to "More", "#", class: "footer-list-header"
              %li 
                =link_to "Register", registration_path, class: "footer-list-item"
              %li 
                =link_to "Contact", contact_path, class: "footer-list-item"
      .col-lg-3.col-6.mx-auto
        %h4 Contact Info 
        %table
          %tr
            %td
              =image_tag "footer-phone-icon.png"
            %td 
              (732) 662-1238 
          %tr 
            %td 
              =image_tag "footer-email-icon.png"
            %td 
              info@veriklick.com 
          %tr 
            %td 
              =image_tag "footer-directions-icon.png"
            %td.text-nowrap
              =render "shared/address"
.pt-1.pb-0
  .container 
    %p.fine-print.m-0
      &copy; 2019 VeriKlick. All Rights Reserved 

app/views/shared/_dropdown-menu-content.html.haml
-(1..3).each do |i| 
  =link_to "Option #{i}", "#", class: "dropdown-item"

app/views/shared/_logo_menu_bar.html.haml
.container.d-none.d-lg-block
  .row.align-items-end.py-3.my--30
    .col-4.justify-content-start
      =link_to root_path, class: "logo" do 
        =image_tag "VeriKlick-Logo.png"
    .col-8.justify-content-end
      %ul.nav.justify-content-end#bold-menu
        %li.nav-item 
          =link_to "Products", "#", class: "nav-link red-underlined"
          .nav-block
            .row.p-2
              .col-lg-4.px-3
                =link_to products_veriklick_path do 
                  .p-2
                    %h3.text-blue<
                      Veri
                      %span.text-red> Klick
                    %p.text-med-gray
                      Recruiting Platform
              .col-lg-4.px-3
                =link_to products_veridial_path do 
                  .p-2
                    %h3.text-blue<
                      Veri
                      %span.text-red> Dial
                    %p.text-med-gray
                      Recruiting Dialer
              .col-lg-4.px-3
                =link_to products_verisource_path do 
                  .p-2
                    %h3.text-blue<
                      Veri
                      %span.text-red> Source
                    %p.text-med-gray
                      Candidate Sourcing
        %li.nav-item 
          =link_to "Pricing", pricing_path, class: "nav-link red-underlined"
        %li.nav-item 
          =link_to "Demo", demo_path, class: "nav-link red-underlined"
        %li.nav-item
          =link_to "Get Started", get_started_path, class: "nav-link btn btn-red"

app/views/shared/_mobile-header.html.haml
.p-0.d-lg-none
  %nav.navbar.navbar-light.bg-light
    =link_to root_path, class: "navbar-brand logo" do 
      =image_tag "VeriKlick-Logo.png"
    %button{:type => "button",
            :data => { toggle: "collapse",
                       target: "#mobile-menu" },
            :aria => { controls: "mobile-menu",
                       expanded: "false",
                       label: "Toggle navigation" },
           :class => "navbar-toggler ml-auto" }
      %span.navbar-toggler-icon 
  .collapse#mobile-menu
    .p-4
      %ul.navbar-nav 
        %li.navbar-nav 
          %h4 
            %strong Products 
          %ul.navbar-nav 
            %li.nav-item 
              =link_to "VeriKlick", products_veriklick_path, class: "nav-link"
            %li.nav-item 
              =link_to "VeriDial", products_veridial_path, class: "nav-link"
            %li.nav-item 
              =link_to "VeriSource", products_verisource_path, class: "nav-link"
        %li.navbar-nav 
          %h4 
            %strong Company
          %ul.navbar-nav 
            %li.nav-item 
              =link_to "About us", about_path, class: "nav-link"
            %li.nav-item 
              =link_to "Careers", careers_path, class: "nav-link"
        %li.navbar-nav 
          %h4 
            %strong Library
          %ul.navbar-nav 
            %li.nav-item 
              =link_to "Blog", blog_path, class: "nav-link"
            %li.nav-item 
              =link_to "Pricing", pricing_path, class: "nav-link"
            %li.nav-item
              =link_to "Demo", demo_path, class: "nav-link"
        %li.navbar-nav 
          %h4 
            %strong More 
          %ul.navbar-nav 
            %li.nav-item 
              =link_to "Register", registration_path, class: "nav-link"
            %li.nav-item 
              =link_to "Contact", contact_path, class: "nav-link"
        %li.navbar-nav 
          =link_to "Support", support_path, class: "nav-link"
        %li.navbar-nav 
          =link_to login_path, class: "nav-link" do 
            =icon "fas", "user"
            Login
        
        

app/views/shared/_top_header.html.haml
.container-fluid.d-none.d-lg-block#top-header
  %ul.nav.justify-content-end.py-2#top-menu
    %li.nav-item
      =link_to "Support", support_path, class: "nav-link red-underlined"
    %li.nav-item.dropdown
      %a.nav-link.dropdown-toggle{ :data => { toggle: "dropdown" },
                                  :class => "red-underlined",
                                   :href => "#",
                                   :role => "button",
                                   :aria => { haspopup: "true", 
                                              expanded: "false" } } 
        Company
      .dropdown-menu
        =link_to "About Us", about_path, class: "dropdown-item"
        =link_to "Careers", careers_path, class: "dropdown-item"
    %li.nav-item.dropdown
      %a.nav-link.dropdown-toggle{ :data => { toggle: "dropdown" },
                                  :class => "red-underlined",
                                   :href => "#",
                                   :role => "button",
                                   :aria => { haspopup: "true", 
                                              expanded: "false" } } 
        Library
      .dropdown-menu
        =link_to "Blog", blog_path, class: "dropdown-item"
    %li.nav-item
      %a.nav-link.red-underlined{ :href => login_path }
        =icon "fas", "user"
        Login